import type { Metadata } from "next";
import Link from "next/link";
import Footer from "./components/Footer";
// import { Head } from "next/document";
import Header from "./components/Header";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ul className="flex gap-2 bg-pink-600">
      
                <li>
                    <Link href="/">Home</Link>
                </li>
                <li><Link href="/">about</Link>About</li>
                <li><Link href="/career"></Link>Careers</li>
                <li><Link href="/contact-us">Contact Us</Link></li>
            </ul>
        {/* // className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
      <h1> No repeatation</h1>
        <h2>Layout</h2>
        {/* <Header/> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
